#export LC_ALL=en_US.UTF-8
fortune | cowsay
# export PATH=/Applications/factor:"$PATH"
export EDITOR="/usr/local/bin/mate -w"
export PATH=${PATH}:/usr/local/mysql/bin/


#test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

alias c='clear'
alias q='exit'
alias band='sudo shutdown -h now'
alias edz='vim ~/.bashrc'
alias mongoose='cd ~/Desktop/MongoDatabase/; ./server.sh'
alias e='emacs -nw'
alias java-practice='cd ~/Documents/Java-Implementations'
alias ofd='open ${1:-.}'

alias dungeon='emacs -batch -l dunnet'
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ls='ls -G'
alias ll='ls -lG'

alias hsql_db_starter='java -cp ~/Downloads/DMGs/hsqldb-2.6.0/hsqldb/lib/hsqldb.jar org.hsqldb.server.Server --database.0 file:mydb --dbname.0 '
alias sqlEditor='java -cp ~/Downloads/DMGs/hsqldb-2.6.0/hsqldb/lib/hsqldb.jar org.hsqldb.util.DatabaseManagerSwing'
# xdb was used 

alias c='clear'
alias band='sudo shutdown -h now'

alias reboot='sudo reboot -h now'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
SHELL_SESSION_HISTORY=0
alias p='python3'
