" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

" For all text files set 'textwidth' to 78 characters.
autocmd FileType text setlocal textwidth=78

set nocp
set shiftwidth=2
set expandtab
set tabstop=4
syntax on 
colorscheme codedark
set ruler 
set number
set showcmd

" Search down into subfolders 
" Provides tab-completion for all file-related tasks
set path+=**
" Display all matching files when we tab complete 
set wildmenu

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
    packadd! matchit
endif
" Disable the arrow keys for habbit formation 
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
